# Generated by Django 5.2.10 on 2026-02-17 21:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('cfa', 'CFA'), ('usd', 'USD')], default='CFA', max_length=10)),
                ('language', models.CharField(choices=[('english', 'En'), ('french', 'Fr')], default='En', max_length=10)),
                ('theme', models.CharField(choices=[('LIGHT', 'light'), ('DARK', 'dark'), ('SYSTEM', 'system')], default='LIGHT', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('accountBalance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('monthlyLimit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('transactions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('walletType', models.CharField(choices=[('root', 'root'), ('standard', 'standard'), ('vault', 'vault')], default='standard', max_length=10)),
                ('status', models.CharField(default='active', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('transactionType', models.CharField(choices=[('Send', 'Cash-out'), ('Receive', 'Cash-in')], default='Send', max_length=20)),
                ('motive', models.CharField(choices=[('rent', 'Rent'), ('shopping', 'Shopping'), ('medicals', 'Medicals'), ('ceremony', 'Ceremony'), ('others', 'Others'), ('salary', 'Salary'), ('business', 'Business'), ('investment', 'Investment'), ('gift', 'Gift'), ('others', 'Others'), ('recharge', 'Recharge')], default='recharge', max_length=50)),
                ('currency', models.CharField(default='CFA', max_length=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Submitted', max_length=25)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('counterpartyWallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.wallet')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to='users.wallet')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
