# Generated by Django 5.2.10 on 2026-02-17 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='note',
            field=models.CharField(blank=True, null=True),
        ),
    ]
