# Generated by Django 5.2.10 on 2026-02-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_transaction_counterparty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='counterparty',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
