# Generated by Django 5.2.10 on 2026-03-25 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microfinances', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('full_names', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=12)),
                ('occupation', models.CharField(max_length=20)),
                ('account_balance', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='microfinances.ledger')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
